bug 1321590: Let's see what the config is

diff --git a/scripts/travis-install b/scripts/travis-install
--- a/scripts/travis-install
+++ b/scripts/travis-install
@@ -49,7 +49,9 @@ then
         sudo ls /etc/init.d
         sudo cat /etc/init.d/mysql || echo "No such file"
         sudo ls /etc/init
-        sudo cat /etc/init/mysql || echo "No such file"
+        sudo cat /etc/init/mysql-5.6.conf || echo "No such file"
+        mysqld_safe || echo "mysqd_safe failed"
+        mysqld || echo "mysql failed"
         exit 1
     fi
 fi
