bug 1321590: Try printing defaults like init

diff --git a/scripts/travis-install b/scripts/travis-install
--- a/scripts/travis-install
+++ b/scripts/travis-install
@@ -50,8 +50,8 @@ then
         sudo cat /etc/init.d/mysql || echo "No such file"
         sudo ls /etc/init
         sudo cat /etc/init/mysql-5.6.conf || echo "No such file"
-        mysqld_safe || echo "mysqd_safe failed"
-        mysqld || echo "mysql failed"
+        sudo my_print_defaults mysqld_safe || echo "mysqd_safe failed"
+        sudo my_print_defaults mysqld || echo "mysql failed"
         exit 1
     fi
 fi
